"""add comments

Revision ID: 169bb9b4a827
Revises: 81540e57506a
Create Date: 2025-08-07 21:12:42.281521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169bb9b4a827'
down_revision = '81540e57506a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
