"""update_document_model_remove_visibility_add_project_and_users

Revision ID: 3c57d24f3bcd
Revises: 7e47ea1c2376
Create Date: 2025-08-12 09:26:12.364424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c57d24f3bcd'
down_revision = '7e47ea1c2376'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True, comment='所属项目ID，为空表示不属于任何项目'))
        batch_op.add_column(sa.Column('specific_user_ids', sa.JSON(), nullable=True, comment='指定可见用户ID列表，为空表示所有用户可见'))
        batch_op.create_foreign_key('fk_document_project_id', 'projects', ['project_id'], ['id'])
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=8), nullable=False))
        batch_op.drop_constraint('fk_document_project_id', type_='foreignkey')
        batch_op.drop_column('specific_user_ids')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
