"""描述

Revision ID: 42fd2f8e52f7
Revises: 9753583dce96
Create Date: 2025-08-07 21:01:30.179962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fd2f8e52f7'
down_revision = '9753583dce96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
