"""20250812v1

Revision ID: 4b5bc4d5b171
Revises: 3c57d24f3bcd
Create Date: 2025-08-12 09:32:19.737343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5bc4d5b171'
down_revision = '3c57d24f3bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 注意: project 表已经存在，跳过创建操作
    # 注意: projects 表已经不存在，跳过删除操作
    
    # 更新外键约束
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_project_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_document_project_id_new', 'project', ['project_id'], ['id'])

    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_project_memberships_project_id', 'project', ['project_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_project_id', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 恢复外键约束
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_project_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_memberships_project_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_document_project_id_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_document_project_id', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###