"""add document tables

Revision ID: 6b146b112c27
Revises: dcd24586c585
Create Date: 2025-08-09 22:17:52.961635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b146b112c27'
down_revision = 'dcd24586c585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_entries',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档内容(Markdown)'),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PROJECT', 'SPECIFIC', 'PRIVATE', name='documentvisibility'), nullable=False, comment='可见性: public/project/specific/private'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档表，记录用户创建的文档（原“日记”）及可见性'
    )
    with op.batch_alter_table('document_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_entries_id'), ['id'], unique=False)

    op.create_table('document_comments',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容(Markdown)'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='文档ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档评论表（独立于通用评论），关联 document_entries'
    )
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comments_id'))
        batch_op.drop_index(batch_op.f('ix_document_comments_document_id'))

    op.drop_table('document_comments')
    with op.batch_alter_table('document_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_entries_id'))

    op.drop_table('document_entries')
    # ### end Alembic commands ###
