"""add document tables1

Revision ID: 7e47ea1c2376
Revises: 6b146b112c27
Create Date: 2025-08-09 22:38:12.824454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e47ea1c2376'
down_revision = '6b146b112c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档内容(Markdown)'),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PROJECT', 'SPECIFIC', 'PRIVATE', name='documentvisibility'), nullable=False, comment='可见性: public/project/specific/private'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档表，记录用户创建的文档及可见性'
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_id'), ['id'], unique=False)

    op.create_table('document_comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容(Markdown)'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='文档ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档评论表（独立于通用评论），关联 document'
    )
    with op.batch_alter_table('document_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comment_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comment_id'), ['id'], unique=False)

    with op.batch_alter_table('document_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_entries_id'))

    op.drop_table('document_entries')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_session_id'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comments_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_comments_id'))

    op.drop_table('document_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comments_document_id'), ['document_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_session_id'), ['session_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_login_sessions_id'), ['id'], unique=False)

    op.create_table('document_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=8), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_entries_id'), ['id'], unique=False)

    with op.batch_alter_table('document_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comment_id'))
        batch_op.drop_index(batch_op.f('ix_document_comment_document_id'))

    op.drop_table('document_comment')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_id'))

    op.drop_table('document')
    # ### end Alembic commands ###
