"""修改users表字段

Revision ID: 933d514448ce
Revises: 169bb9b4a827
Create Date: 2025-08-08 18:02:35.597286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933d514448ce'
down_revision = '169bb9b4a827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='普通用户', nullable=False, comment='角色: 普通用户|管理员'))
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_column('users', 'unionid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unionid', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=1)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
