"""描述

Revision ID: 9d386314a045
Revises: 42fd2f8e52f7
Create Date: 2025-08-07 21:02:42.652621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d386314a045'
down_revision = '42fd2f8e52f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
