"""20250812v3

Revision ID: ad0f8a662bac
Revises: b6edfe31b48a
Create Date: 2025-08-12 16:12:16.010092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0f8a662bac'
down_revision = 'b6edfe31b48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='消息类型'),
    sa.Column('level', sa.String(length=20), server_default='info', nullable=False, comment='级别: info|warning|error'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='人类可读说明'),
    sa.Column('entity_type', sa.String(length=30), nullable=True, comment='关联实体类型: contract|document|task|project'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='关联实体ID'),
    sa.Column('actor_id', sa.Integer(), nullable=True, comment='触发者用户ID，系统产生可为空'),
    sa.Column('data_json', sa.Text(), nullable=True, comment='结构化上下文JSON'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统消息主表，描述消息事件本身'
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_id'), ['id'], unique=False)

    op.create_table('message_recipient',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='消息ID'),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False, comment='接收人用户ID'),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('delivered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='投递时间'),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='消息接收关系表，记录每个接收人的投递与已读状态'
    )
    with op.batch_alter_table('message_recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_recipient_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_read'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))

    op.drop_table('message_recipient')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
